/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MesesRouteImport } from './routes/meses'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtletasRouteImport } from './routes/atletas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesesIdRouteImport } from './routes/meses.$id'
import { Route as AtletasIdRouteImport } from './routes/atletas.$id'

const MesesRoute = MesesRouteImport.update({
  id: '/meses',
  path: '/meses',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasRoute = AtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesesIdRoute = MesesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MesesRoute,
} as any)
const AtletasIdRoute = AtletasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AtletasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRouteWithChildren
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/meses': typeof MesesRouteWithChildren
  '/atletas/$id': typeof AtletasIdRoute
  '/meses/$id': typeof MesesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRouteWithChildren
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/meses': typeof MesesRouteWithChildren
  '/atletas/$id': typeof AtletasIdRoute
  '/meses/$id': typeof MesesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRouteWithChildren
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/meses': typeof MesesRouteWithChildren
  '/atletas/$id': typeof AtletasIdRoute
  '/meses/$id': typeof MesesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atletas'
    | '/auth'
    | '/importar'
    | '/meses'
    | '/atletas/$id'
    | '/meses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atletas'
    | '/auth'
    | '/importar'
    | '/meses'
    | '/atletas/$id'
    | '/meses/$id'
  id:
    | '__root__'
    | '/'
    | '/atletas'
    | '/auth'
    | '/importar'
    | '/meses'
    | '/atletas/$id'
    | '/meses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtletasRoute: typeof AtletasRouteWithChildren
  AuthRoute: typeof AuthRoute
  ImportarRoute: typeof ImportarRoute
  MesesRoute: typeof MesesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meses': {
      id: '/meses'
      path: '/meses'
      fullPath: '/meses'
      preLoaderRoute: typeof MesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas': {
      id: '/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AtletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meses/$id': {
      id: '/meses/$id'
      path: '/$id'
      fullPath: '/meses/$id'
      preLoaderRoute: typeof MesesIdRouteImport
      parentRoute: typeof MesesRoute
    }
    '/atletas/$id': {
      id: '/atletas/$id'
      path: '/$id'
      fullPath: '/atletas/$id'
      preLoaderRoute: typeof AtletasIdRouteImport
      parentRoute: typeof AtletasRoute
    }
  }
}

interface AtletasRouteChildren {
  AtletasIdRoute: typeof AtletasIdRoute
}

const AtletasRouteChildren: AtletasRouteChildren = {
  AtletasIdRoute: AtletasIdRoute,
}

const AtletasRouteWithChildren =
  AtletasRoute._addFileChildren(AtletasRouteChildren)

interface MesesRouteChildren {
  MesesIdRoute: typeof MesesIdRoute
}

const MesesRouteChildren: MesesRouteChildren = {
  MesesIdRoute: MesesIdRoute,
}

const MesesRouteWithChildren = MesesRoute._addFileChildren(MesesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtletasRoute: AtletasRouteWithChildren,
  AuthRoute: AuthRoute,
  ImportarRoute: ImportarRoute,
  MesesRoute: MesesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
