/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesesIndexRouteImport } from './routes/meses.index'
import { Route as AtletasIndexRouteImport } from './routes/atletas.index'
import { Route as MesesIdRouteImport } from './routes/meses.$id'
import { Route as AtletasIdRouteImport } from './routes/atletas.$id'

const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesesIndexRoute = MesesIndexRouteImport.update({
  id: '/meses/',
  path: '/meses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasIndexRoute = AtletasIndexRouteImport.update({
  id: '/atletas/',
  path: '/atletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesesIdRoute = MesesIdRouteImport.update({
  id: '/meses/$id',
  path: '/meses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasIdRoute = AtletasIdRouteImport.update({
  id: '/atletas/$id',
  path: '/atletas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/atletas/$id': typeof AtletasIdRoute
  '/meses/$id': typeof MesesIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/meses/': typeof MesesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/atletas/$id': typeof AtletasIdRoute
  '/meses/$id': typeof MesesIdRoute
  '/atletas': typeof AtletasIndexRoute
  '/meses': typeof MesesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/atletas/$id': typeof AtletasIdRoute
  '/meses/$id': typeof MesesIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/meses/': typeof MesesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/importar'
    | '/atletas/$id'
    | '/meses/$id'
    | '/atletas/'
    | '/meses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/importar'
    | '/atletas/$id'
    | '/meses/$id'
    | '/atletas'
    | '/meses'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/importar'
    | '/atletas/$id'
    | '/meses/$id'
    | '/atletas/'
    | '/meses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ImportarRoute: typeof ImportarRoute
  AtletasIdRoute: typeof AtletasIdRoute
  MesesIdRoute: typeof MesesIdRoute
  AtletasIndexRoute: typeof AtletasIndexRoute
  MesesIndexRoute: typeof MesesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meses/': {
      id: '/meses/'
      path: '/meses'
      fullPath: '/meses/'
      preLoaderRoute: typeof MesesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/': {
      id: '/atletas/'
      path: '/atletas'
      fullPath: '/atletas/'
      preLoaderRoute: typeof AtletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meses/$id': {
      id: '/meses/$id'
      path: '/meses/$id'
      fullPath: '/meses/$id'
      preLoaderRoute: typeof MesesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/$id': {
      id: '/atletas/$id'
      path: '/atletas/$id'
      fullPath: '/atletas/$id'
      preLoaderRoute: typeof AtletasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ImportarRoute: ImportarRoute,
  AtletasIdRoute: AtletasIdRoute,
  MesesIdRoute: MesesIdRoute,
  AtletasIndexRoute: AtletasIndexRoute,
  MesesIndexRoute: MesesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
